#!/bin/bash

# Fuzzy find and run a github/github test
# Requires selecta:
# https://github.com/garybernhardt/selecta

command -v selecta >/dev/null 2>&1 || { echo >&2 "I require selecta but it's not installed. Aborting."; exit 1; }

GITHUB_REPO=$HOME/github/github
TESTRB=$GITHUB_REPO/bin/testrb

TEST_FILE=$(find $GITHUB_REPO/test -iname "*_test\.rb" | selecta)
clear

echo "$TESTRB $TEST_FILE"
echo
cd $GITHUB_REPO
$TESTRB $TEST_FILE
