#!/bin/bash

# Fuzzy find and run a github/github test
# Requires selecta:
# https://github.com/garybernhardt/selecta

command -v selecta >/dev/null 2>&1 || { echo >&2 "I require selecta but it's not installed. Aborting."; exit 1; }

GITHUB_REPO=$HOME/github/github
TESTRB=$GITHUB_REPO/bin/testrb

TEST_FILE=$(find $GITHUB_REPO/test -iname "*_test\.rb" | selecta)
clear

echo "Running tests: $TEST_FILE"
echo "$TESTRB $TEST_FILE" |pbcopy
echo
cd $GITHUB_REPO

TEST_ALL_FEATURES=1 $TESTRB $TEST_FILE
